name: tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-full-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache NLTK data
      uses: actions/cache@v4
      with:
        path: ~/.nltk_data
        key: ${{ runner.os }}-nltk-${{ hashFiles('**/requirements.txt') }}
    - name: Install PostgreSQL
      run: |
        apt-get update
        apt-get install -y libpq-dev
    - name: Install Build Essentials for PSQL and GDAL
      run: |
        apt-get install -y build-essential
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Download NLTK data
      run: |
        python -m nltk.downloader punkt
    - name: Test with pytest
      run: |
        python -m pytest
